### ISSUE TITLE
didn't work without an action

### ISSUE THREAD

**Issue by udisun** [socialtables/redux-unhandled-action#5] opened 2016-08-07 06:40 UTC
basically without passing a function this broke the redux entirely

**Comment by conorhastings** [comment] 2016-08-07 14:32
@udisun do you have an example?

**Comment by conorhastings** [comment] 2016-08-14 16:19
@udisun closing since there is no reproducable case, please reopen/make a new issue if you're still having issues

**Closed as completed by conorhastings** 2016-08-14 16:19 UTC
